name: update DAGs airflow

on:
  push:
    branches:
      - main

jobs:
  update-dags:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: 123.45.67.89
      SERVER_USER: root
      SSH_PRIVATE_KEY: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        ...
        -----END OPENSSH PRIVATE KEY-----
      DECRYPT_PRIVAT_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SCP
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          echo "$DECRYPT_PRIVAT_KEY" > private_key.pem
          chmod 600 key.pem
          chmod 600 private_key.pem

          mkdir -p $HOME/.ssh
          ssh-keyscan -H $SERVER_IP >> $HOME/.ssh/known_hosts

          sudo apt-get update && sudo apt-get install -y openssl
          openssl rsa -in private_key.pem -check

          for archive in encrypted_file/*.tar.gz; do
            echo "Decrypting $archive..."
            ./decrypt_and_extract.sh "$archive" private_key.pem
          done

          rsync -rav -e "ssh -i key.pem" --delete-after \
            --exclude "key.pem" --exclude "private_key.pem" --exclude "*.tar.gz" \
            ./ $SERVER_USER@$SERVER_IP:/root/airflow-docker/dags
